name: testgitaction1
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: 1/ print hello with name 
        run: echo "hello oussama 47"
      - name: 2/ checkout repo
        uses: actions/checkout@v6.0.1
      - name: 3/ print repo content
        run: ls -la
